### ISSUE TITLE
Provide documentation on how to create and self-sign certificates

### ISSUE THREAD

**Issue by nixigaj** [M0dEx/quincy#3]

**Comment by M0dEx** [comment]
Hello!

This is a good suggestion, as currently, due to strict rules of `rustls`, you have to have a self-signed CA certificate and use it to sign a server certificate with SAN (Subject Alternate Names).

I would like Quincy to accept simple self-signed certificates as well, as long as they are trusted by the client.

I'm going to look into this.

**Comment by M0dEx** [comment]
Turns out I was wrong - `rustls` can accept a self-signed certificate as long as it is trusted.

It just has to have the `CA` constraint in x509 v3 extensions set to `FALSE`.

I will add a README section for certificate generation.
