### ISSUE TITLE
Lets Encrypt private key compatibility

### ISSUE THREAD

**Issue by bitzbyte** [M0dEx/quincy#68]
Lets Encrypt private key files have the following format:

```
-----BEGIN EC PRIVATE KEY-----
{{key mat}}
-----END EC PRIVATE KEY-----
```

When Quincy is configured to use that file it results in the following error:

> ERROR quincy_server: A critical error occurred: No private key found in the file: ...

Removing "EC" from the prefix and suffix resolves the error.

**Comment by M0dEx** [comment]
Hi!

Since `rustls` is used as the underlying cryptographic library, there is little that could be done in Quincy to support keys in this format.

However, as per the relevant `rustls` issue (https://github.com/rustls/rustls/issues/767), it should be possible to easily transform the elliptic key format into a PKCS8-compatible one with `openssl`:
```bash
openssl pkcs8 -topk8 -nocrypt -in ec_key.pem -out pkcs8_key.pem
```

**Comment by bitzbyte** [comment]
Makes sense. Thanks for the quick response!
